export const eat = [
  {
    id: 1,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 1,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 2,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 2,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 3,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 3,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 4,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 4,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 5,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 5,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 6,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 6,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 7,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 7,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
  {
    id: 8,
    img: "/public/assets/public api/birdEat2.png",
    name: "Корм для птиц RIO Линька",
    descriptions: "для волнистых попугайчиков",
    price: "1000 руб.",
    quantity: 1,
    gramms: [
      {
        id: 8,
        gramm1: "200 г",
        gramm2: "400 г",
        gramm3: "800 г",
        gramm4: "1 кг",
      },
    ],
  },
];
