export const izba = [
  {
    id: 1,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 2,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 3,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 4,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 5,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 6,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 7,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
  {
    id: 8,
    img: "src/shared/assets/public api/izba.png",
    name: 'Комплект-агро "Избушка на курьих ножках"',
    descriptions: "кормушка малая",
    price: "1000 руб.",
  },
];
